### ISSUE TITLE
where is the Dockerfile for the "php hack" container?

### ISSUE THREAD

**Issue by JannikZed** [TrurlMcByte/docker-php-fpm#1]
Hi there,
I came here from the Digitalocean support forums where you posted your own PHP hack version to work with the Digitalocean hosted mysql. 
I kindly wanted to ask you, if you could provide this dockerfile as well, as we need to get a wordpress container running as well and I don't know what you did to get the PHP running.

**Comment by JannikZed** [comment]
Any help possible? I would like to take-over support for this image and upgrade some packages as well as the underlying alpine linux ..

**Comment by TrurlMcByte** [comment]
[php5.zip](https://github.com/TrurlMcByte/docker-php-fpm/files/4874765/php5.zip)
